apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab-pv
  labels:
    usage: lab-data
    app: lab
spec:
  storageClassName: "manual"
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    # local storage directory
    path: ""
