apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: lab
  name: lab-pvc
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
  selector:
    matchLabels:
      usage: lab-data
