apiVersion: v1
kind: Service
metadata:
  name: lab-nodeport-svc
  namespace: lab
spec:
  type: NodePort
  selector:
    app: lab
  ports:
    - port: 2368
      targetPort: 2368
      nodePort: 32368
